[package]
name = "injector"
version = "0.1.0"
edition = "2024"

[dependencies]
injector-derive = { path = "../injector-derive" }

linkme = { version = "0.3", used_linker = true }
multimap = {  version = "0.10.0", default-features = false }
